sdk: "/Library/Ruby/Gems/1.8/gems/rhodes-1.2.2"
name: rutanetmobile
version: 1.2.2
vendor: rhomobile
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Debug
  sdk: iphonesimulator3.0
  codesignidentity:
  entitlements: 