--- 
name: rutanetmobile
bbver: 4.6
sdk: /Users/fede/.rvm/gems/ruby/1.8.7/gems/rhodes-1.2.2
applog: rholog.txt
version: 1.2.2
vendor: rhomobile
iphone: 
  sdk: iphonesimulator3.0
  entitlements: 
  codesignidentity: 
  configuration: Debug
