--- 
name: rutanetmobile
bbver: 4.6
sdk: /Library/Ruby/Gems/1.8/gems/rhodes-1.2.2
applog: rholog.txt
version: 1.4.0
vendor: rhomobile
iphone: 
  sdk: iphonesimulator3.0
  entitlements: 
  codesignidentity: 
  configuration: Debug
